services:
  - type: web
    name: gameon
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: gameon-db
          property: connectionString
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: gameon-db
    plan: free
    postgresMajorVersion: "16" 